export const DIMENSIONS = ["quiet", "uncrowded", "daylight", "seating"];

export const DIMENSION_LABELS = {
  quiet: "安静度",
  uncrowded: "低拥挤",
  daylight: "自然光",
  seating: "座位友好",
};

export const SCENARIOS = {
  deepWork: {
    label: "深度工作",
    description: "更在意低声量和稳定座位",
    preferences: { quiet: 95, uncrowded: 82, daylight: 52, seating: 88 },
  },
  unwind: {
    label: "放松休息",
    description: "光线柔和，人流节奏更慢",
    preferences: { quiet: 78, uncrowded: 86, daylight: 82, seating: 65 },
  },
  social: {
    label: "轻松聊天",
    description: "容许背景声，更在意空间与光线",
    preferences: { quiet: 48, uncrowded: 62, daylight: 80, seating: 74 },
  },
};

export const VISIT_TIMES = {
  weekdayMorning: "工作日早晨",
  weekdayAfternoon: "工作日下午",
  weekend: "周末",
};

export const CAFES = [
  {
    id: "hp-naive",
    name: "naive 理想国 coffee · bar",
    shortName: "naive 理想国 coffee · bar",
    district: "黄浦区",
    address: "洛克外滩源虎丘路78号",
    scores: { quiet: 89, uncrowded: 77, daylight: 71, seating: 86 },
    confidence: 86,
    bestTime: "工作日 10:00–15:00",
    weekendPenalty: 15,
    position: [31.243456, 121.484416],
    mapPosition: [560, 884],
    scene: "/assets/cafes/naive-watercolor-v2.png",
    conflict: "15:30 后人流上升",
    evidence: "工作日下午背景音乐稳定，交谈声较低。",
    sourceStatus: "门店实拍已核实，感官证据待逐条审核",
  },
  {
    id: "hp-omnibus",
    name: "Omnibus Coffee",
    shortName: "Omnibus Coffee",
    district: "黄浦区",
    address: "宁波路620弄3-21号",
    scores: { quiet: 92, uncrowded: 85, daylight: 64, seating: 73 },
    confidence: 81,
    bestTime: "工作日 09:00–15:00",
    weekendPenalty: 9,
    position: [31.238069, 121.472117],
    mapPosition: [583, 820],
    conflict: "小桌面不适合多人协作",
    evidence: "弄堂内部减少车流声，但座位规模有限。",
    sourceStatus: "研究核实中",
  },
  {
    id: "hp-cafe-on-air",
    name: "CAFE ON AIR（淮海路店）",
    shortName: "CAFE ON AIR",
    district: "黄浦区",
    address: "淮海中路650弄634号",
    scores: { quiet: 80, uncrowded: 70, daylight: 88, seating: 82 },
    confidence: 82,
    bestTime: "工作日 10:00–14:00",
    weekendPenalty: 17,
    position: [31.221654, 121.462969],
    mapPosition: [510, 760],
    conflict: "下午茶时段客流集中",
    evidence: "白天光线充足，桌高与靠背适合阅读写作。",
    sourceStatus: "研究核实中",
  },
  {
    id: "hp-blue-house",
    name: "蓝屋咖啡",
    shortName: "蓝屋咖啡",
    district: "黄浦区",
    address: "局门路468号八号桥创意园2期",
    scores: { quiet: 76, uncrowded: 70, daylight: 70, seating: 74 },
    confidence: 80,
    bestTime: "工作日 10:00–16:00",
    weekendPenalty: 8,
    position: [31.204121, 121.478929],
    mapPosition: [458, 872],
    conflict: "部分内侧座位自然光偏弱",
    evidence: "园区位置减少随机客流，固定桌面适合连续任务。",
    sourceStatus: "研究核实中",
  },
  {
    id: "hp-metal-hands",
    name: "铁手咖啡制造局",
    shortName: "Metal Hands",
    district: "黄浦区",
    address: "永嘉路37号",
    scores: { quiet: 77, uncrowded: 70, daylight: 76, seating: 63 },
    confidence: 62,
    bestTime: "工作日上午",
    weekendPenalty: 16,
    position: [31.211894, 121.459401],
    mapPosition: [480, 745],
    conflict: "高峰期座位周转较快",
    evidence: "精品咖啡出品节奏明确，更适合一小时内任务。",
    sourceStatus: "研究核实中",
  },
  {
    id: "hp-antique",
    name: "古董花园 · Antique",
    shortName: "古董花园",
    district: "黄浦区",
    address: "思南路44号",
    scores: { quiet: 81, uncrowded: 71, daylight: 86, seating: 79 },
    confidence: 66,
    bestTime: "工作日早晨",
    weekendPenalty: 20,
    position: [31.217950, 121.463645],
    mapPosition: [494, 782],
    conflict: "周末花园客流可能上升",
    evidence: "花园光线与座位适合阅读，周末波动需进一步验证。",
    sourceStatus: "研究核实中",
  },
  {
    id: "hp-always",
    name: "Always Coffee Roaster",
    shortName: "Always Coffee",
    district: "黄浦区",
    address: "九江路501号106室",
    scores: { quiet: 75, uncrowded: 64, daylight: 72, seating: 68 },
    confidence: 61,
    bestTime: "工作日上午",
    weekendPenalty: 17,
    position: [31.236983, 121.478606],
    mapPosition: [548, 842],
    conflict: "中心城区人流波动较大",
    evidence: "交通便利，但体验对到店时段更敏感。",
    sourceStatus: "研究核实中",
  },
  {
    id: "hp-shiteng",
    name: "石藤咖啡（人民广场店）",
    shortName: "石藤咖啡",
    district: "黄浦区",
    address: "威海路20-2号",
    scores: { quiet: 74, uncrowded: 67, daylight: 61, seating: 70 },
    confidence: 60,
    bestTime: "工作日午前",
    weekendPenalty: 15,
    position: [31.229676, 121.467366],
    mapPosition: [535, 803],
    conflict: "更适合短时处理任务",
    evidence: "低预算候选，不建议将连续久坐作为默认预期。",
    sourceStatus: "研究核实中",
  },
  {
    id: "hp-naive-tree",
    name: "村口大树（长乐路店）",
    shortName: "村口大树",
    district: "黄浦区",
    address: "长乐路366弄幸福公寓",
    scores: { quiet: 84, uncrowded: 80, daylight: 67, seating: 68 },
    confidence: 64,
    bestTime: "工作日下午",
    weekendPenalty: 10,
    position: [31.222483, 121.458599],
    mapPosition: [501, 718],
    conflict: "座位数量需实时确认",
    evidence: "社区位置有利于低刺激体验，小体量带来座位不确定。",
    sourceStatus: "研究核实中",
  },
  {
    id: "hp-east-sea",
    name: "东海咖啡馆",
    shortName: "东海咖啡馆",
    district: "黄浦区",
    address: "滇池路110号",
    scores: { quiet: 82, uncrowded: 73, daylight: 58, seating: 75 },
    confidence: 63,
    bestTime: "工作日上午",
    weekendPenalty: 13,
    position: [31.241043, 121.484615],
    mapPosition: [575, 906],
    conflict: "部分座位自然光偏弱",
    evidence: "老店空间具有低声量潜力，光线因座位不同而波动。",
    sourceStatus: "研究核实中",
  },
];
