export const DIMENSIONS = ["quiet", "uncrowded", "daylight", "seating"];

export const DIMENSION_LABELS = {
  quiet: "安静度",
  uncrowded: "低拥挤",
  daylight: "自然光",
  seating: "座位友好",
};

export const SCENARIOS = {
  deepWork: {
    label: "深度工作",
    description: "更在意低声量和稳定座位",
    preferences: { quiet: 95, uncrowded: 82, daylight: 52, seating: 88 },
  },
  unwind: {
    label: "放松休息",
    description: "光线柔和，人流节奏更慢",
    preferences: { quiet: 78, uncrowded: 86, daylight: 82, seating: 65 },
  },
  social: {
    label: "轻松聊天",
    description: "容许背景声，更在意空间与光线",
    preferences: { quiet: 48, uncrowded: 62, daylight: 80, seating: 74 },
  },
};

export const VISIT_TIMES = {
  weekdayMorning: "工作日早晨",
  weekdayAfternoon: "工作日下午",
  weekend: "周末",
};

export const CAFES = [
  {
    id: "hp-naive",
    name: "naive 理想国 coffee · bar",
    shortName: "naive 理想国 coffee · bar",
    district: "黄浦区",
    address: "洛克外滩源虎丘路78号",
    scores: { quiet: 89, uncrowded: 77, daylight: 71, seating: 86 },
    confidence: 86,
    bestTime: "工作日 10:00–15:00",
    weekendPenalty: 15,
    position: [31.243456, 121.484416],
    scene: "/assets/cafes/naive-watercolor- v1.png",
    conflict: "15:30 后人流上升",
    evidence: "工作日下午背景音乐稳定，交谈声较低。",
    sourceStatus: "门店实拍已核实，感官证据待逐条审核",
  },
  {
    id: "hp-omnibus",
    name: "Omnibus Coffee",
    shortName: "Omnibus Coffee",
    district: "黄浦区",
    address: "宁波路620弄3-21号",
    scores: { quiet: 92, uncrowded: 85, daylight: 64, seating: 73 },
    confidence: 81,
    bestTime: "工作日 09:00–15:00",
    weekendPenalty: 9,
    position: [31.238069, 121.472117],
    scene: "/assets/cafes/omnibus-watercolor-v1.png",
    conflict: "座位情况待核实",
    evidence: "企鹅吃喝指南多次回访：店内白板展示每日手冲参数，空间以巴士主题为主。",
    sourceStatus: "门店、地址与实拍已交叉核实；感官分数待现场采样",
  },
  {
    id: "hp-cafe-on-air",
    name: "CAFE ON AIR（淮海路店）",
    shortName: "CAFE ON AIR",
    district: "黄浦区",
    address: "淮海中路650弄634号",
    scores: { quiet: 80, uncrowded: 70, daylight: 88, seating: 82 },
    confidence: 82,
    bestTime: "工作日 10:00–12:30",
    weekendPenalty: 17,
    position: [31.222192, 121.461699],
    scene: "/assets/cafes/cafe-on-air-watercolor-v1.png",
    conflict: "13:00 后易满座",
    evidence: "企鹅吃喝指南实访：多数人安静办公，大窗采光充足，长桌插座多；13:00 已接近满座。",
    sourceStatus: "门店、地址、实拍与感官证据已交叉核实；分数为编辑估计",
  },
  {
    id: "hp-blue-house",
    name: "蓝屋咖啡",
    shortName: "蓝屋咖啡",
    district: "黄浦区",
    address: "局门路468号101a",
    scores: { quiet: 76, uncrowded: 70, daylight: 70, seating: 74 },
    confidence: 80,
    bestTime: "工作日上午（待现场采样）",
    weekendPenalty: 8,
    position: [31.20499, 121.47704],
    scene: "/assets/cafes/blue-house-watercolor-v1.png",
    conflict: "银杏季户外人流上升",
    evidence: "记者走访确认窗边与户外座位；安静度与工作适配仍待现场采样。",
    sourceStatus: "门店、地址、坐标与实拍已交叉核实；感官分数待现场采样",
  },
  {
    id: "hp-metal-hands",
    name: "铁手咖啡制造局",
    shortName: "Metal Hands",
    district: "黄浦区",
    address: "永嘉路37号",
    scores: { quiet: 77, uncrowded: 70, daylight: 76, seating: 63 },
    confidence: 79,
    bestTime: "避开早高峰（待现场采样）",
    weekendPenalty: 16,
    position: [31.21155, 121.459023],
    scene: "/assets/cafes/metal-hands-yongjia-watercolor-v1.png",
    conflict: "早高峰通勤客流集中",
    evidence: "永嘉路店采访确认木质书架、后花园玻璃窗和户外座位；早高峰客流较多。",
    sourceStatus: "门店、地址、坐标与实拍已交叉核实；感官分数待现场采样",
  },
  {
    id: "hp-antique",
    name: "古董花园 · Antique",
    shortName: "古董花园",
    district: "黄浦区",
    address: "思南路44号甲",
    scores: { quiet: 81, uncrowded: 71, daylight: 86, seating: 79 },
    confidence: 78,
    bestTime: "避开下午茶高峰（待现场采样）",
    weekendPenalty: 20,
    position: [31.219258, 121.461451],
    scene: "/assets/cafes/antique-garden-watercolor-v1.png",
    conflict: "下午茶时段座位紧张",
    evidence: "2024 实访确认两层古董空间、庭院与靠窗座位；下午较难抢座。",
    sourceStatus: "门店、地址、坐标与实拍已交叉核实；感官分数待现场采样",
  },
  {
    id: "hp-one-tenth",
    name: "1/10 COFFEE ROASTER",
    shortName: "1/10 COFFEE",
    district: "黄浦区",
    address: "九江路501号105室",
    scores: { quiet: 75, uncrowded: 64, daylight: 72, seating: 68 },
    confidence: 74,
    bestTime: "工作日上午（待现场采样）",
    weekendPenalty: 17,
    position: [31.237554, 121.47742],
    scene: "/assets/cafes/one-tenth-jiujiang-watercolor-v1.png",
    conflict: "中心商圈客流待核实",
    evidence: "当前地图实拍确认窄幅木框临街立面；座位、声量与客流仍待现场核实。",
    sourceStatus: "品牌纠错、门店、地址、坐标与实拍已交叉核实；感官分数待现场采样",
  },
  {
    id: "hp-shiteng",
    name: "石藤咖啡（人民广场店）",
    shortName: "石藤咖啡",
    district: "黄浦区",
    address: "威海路20-2号",
    scores: { quiet: 74, uncrowded: 67, daylight: 61, seating: 70 },
    confidence: 72,
    bestTime: "避开高峰（待现场采样）",
    weekendPenalty: 15,
    position: [31.230216, 121.4661],
    scene: "/assets/cafes/shiteng-people-square-watercolor-v1.png",
    conflict: "店内座位较少",
    evidence: "近期实访确认小体量门店、半开放窗台与少量座位。",
    sourceStatus: "门店、地址、坐标与实拍已交叉核实；感官分数待现场采样",
  },
  {
    id: "hp-naive-tree",
    name: "村口大树（长乐路店）",
    shortName: "村口大树",
    district: "黄浦区",
    address: "长乐路366弄1-32号幸福公寓",
    scores: { quiet: 84, uncrowded: 80, daylight: 67, seating: 68 },
    confidence: 72,
    bestTime: "避开高峰（待现场采样）",
    weekendPenalty: 10,
    position: [31.22305, 121.457325],
    scene: "/assets/cafes/naive-tree-changle-watercolor-v1.png",
    conflict: "22㎡小店座位有限",
    evidence: "门店资料确认22㎡小体量空间、室外折叠椅与紧凑客座。",
    sourceStatus: "门店、地址、坐标与实拍已交叉核实；门牌差异已记录；感官分数待现场采样",
  },
  {
    id: "hp-east-sea",
    name: "东海咖啡馆",
    shortName: "东海咖啡馆",
    district: "黄浦区",
    address: "滇池路110号",
    scores: { quiet: 82, uncrowded: 73, daylight: 58, seating: 75 },
    confidence: 63,
    bestTime: "工作日上午",
    weekendPenalty: 13,
    position: [31.241043, 121.484615],
    conflict: "部分座位自然光偏弱",
    evidence: "老店空间具有低声量潜力，光线因座位不同而波动。",
    sourceStatus: "研究核实中",
  },
];
